#!/bin/sh

mkdir -p proprietary

adb pull /system/lib/libmoto_gps.so proprietary/libmoto_gps.so
adb pull /system/lib/libaudio.so proprietary/libaudio.so
adb pull /system/lib/libaudiopolicy.so proprietary/libaudiopolicy.so
adb pull /system/lib/libcamera.so proprietary/libcamera.so
adb pull /system/lib/libril_rds.so proprietary/libril_rds.so
adb pull /system/lib/libnmea.so proprietary/libnmea.so

#adb pull /system/bin/wlan_cu proprietary/wlan_cu
#adb pull /system/bin/wlan_loader proprietary/wlan_loader
#adb pull /system/bin/wpa_supplicant proprietary/wpa_supplicant
#adb pull /system/lib/libwpa_client.so proprietary/libwpa_client.so

adb pull /system/bin/SaveBPVer proprietary/SaveBPVer
adb pull /system/bin/akmd2 proprietary/akmd2
adb pull /system/bin/ap_gain.bin proprietary/ap_gain.bin
adb pull /system/bin/battd proprietary/battd
adb pull /system/bin/bthelp proprietary/bthelp
adb pull /system/bin/chat-ril proprietary/chat-ril
adb pull /system/bin/ftmipcd proprietary/ftmipcd
adb pull /system/bin/mdm_panicd proprietary/mdm_panicd
adb pull /system/bin/picd proprietary/picd
adb pull /system/bin/pppd-ril proprietary/pppd-ril
adb pull /system/bin/pvrsrvinit proprietary/pvrsrvinit
adb pull /system/bin/tcmd proprietary/tcmd
adb pull /system/etc/01_Vendor_ti_omx.cfg proprietary/01_Vendor_ti_omx.cfg
adb pull /system/etc/cameraCalFileDef.bin proprietary/cameraCalFileDef.bin
adb pull /system/etc/excluded-input-devices.xml proprietary/excluded-input-devices.xml
adb pull /system/etc/firmware/wl1271.bin proprietary/wl1271.bin
adb pull /system/etc/gps.conf proprietary/gps.conf
adb pull /system/etc/motorola/12m/key_code_map.txt proprietary/key_code_map.txt
adb pull /system/etc/permissions/android.hardware.camera.flash-autofocus.xml proprietary/android.hardware.camera.flash-autofocus.xml
adb pull /system/etc/permissions/android.hardware.sensor.light.xml proprietary/android.hardware.sensor.light.xml
adb pull /system/etc/permissions/android.hardware.sensor.proximity.xml proprietary/android.hardware.sensor.proximity.xml
adb pull /system/etc/permissions/android.hardware.telephony.cdma.xml proprietary/android.hardware.telephony.cdma.xml
adb pull /system/etc/permissions/android.hardware.touchscreen.multitouch.xml proprietary/android.hardware.touchscreen.multitouch.xml
adb pull /system/etc/ppp/peers/pppd-ril.options proprietary/pppd-ril.options
adb pull /system/etc/pvasflocal.cfg proprietary/pvasflocal.cfg
adb pull /system/etc/vendor/cpcap/macro_data proprietary/macro_data
adb pull /system/etc/vendor/cpcap/vector_data proprietary/vector_data
adb pull /system/etc/vold.conf proprietary/vold.conf
adb pull /system/etc/wifi/fw_wlan1271.bin proprietary/fw_wlan1271.bin
adb pull /system/lib/dsp/baseimage.dof proprietary/baseimage.dof
adb pull /system/lib/dsp/conversions.dll64P proprietary/conversions.dll64P
adb pull /system/lib/dsp/h264vdec_sn.dll64P proprietary/h264vdec_sn.dll64P
adb pull /system/lib/dsp/h264venc_sn.dll64P proprietary/h264venc_sn.dll64P
adb pull /system/lib/dsp/jpegenc_sn.dll64P proprietary/jpegenc_sn.dll64P
adb pull /system/lib/dsp/m4venc_sn.dll64P proprietary/m4venc_sn.dll64P
adb pull /system/lib/dsp/mp4vdec_sn.dll64P proprietary/mp4vdec_sn.dll64P
adb pull /system/lib/dsp/mpeg4aacenc_sn.dll64P proprietary/mpeg4aacenc_sn.dll64P
adb pull /system/lib/dsp/nbamrenc_sn.dll64P proprietary/nbamrenc_sn.dll64P
adb pull /system/lib/dsp/postprocessor_dualout.dll64P proprietary/postprocessor_dualout.dll64P
adb pull /system/lib/dsp/ringio.dll64P proprietary/ringio.dll64P
adb pull /system/lib/dsp/usn.dll64P proprietary/usn.dll64P
adb pull /system/lib/dsp/wbamrenc_sn.dll64P proprietary/wbamrenc_sn.dll64P
adb pull /system/lib/egl/libEGL_POWERVR_SGX530_121.so proprietary/libEGL_POWERVR_SGX530_121.so
adb pull /system/lib/egl/libGLESv1_CM_POWERVR_SGX530_121.so proprietary/libGLESv1_CM_POWERVR_SGX530_121.so
adb pull /system/lib/egl/libGLESv2_POWERVR_SGX530_121.so proprietary/libGLESv2_POWERVR_SGX530_121.so
adb pull /system/lib/hw/gralloc.omap3.so proprietary/gralloc.omap3.so
adb pull /system/lib/hw/lights.sholes.so proprietary/lights.sholes.so
adb pull /system/lib/hw/sensors.sholes.so proprietary/sensors.sholes.so
adb pull /system/lib/libHPImgApi.so proprietary/libHPImgApi.so
adb pull /system/lib/libIMGegl.so proprietary/libIMGegl.so
adb pull /system/lib/libLCML.so proprietary/libLCML.so
adb pull /system/lib/libOMX.TI.AAC.encode.so proprietary/libOMX.TI.AAC.encode.so
adb pull /system/lib/libOMX.TI.AMR.encode.so proprietary/libOMX.TI.AMR.encode.so
adb pull /system/lib/libOMX.TI.JPEG.Encoder.so proprietary/libOMX.TI.JPEG.Encoder.so
adb pull /system/lib/libOMX.TI.Video.Decoder.so proprietary/libOMX.TI.Video.Decoder.so
adb pull /system/lib/libOMX.TI.Video.encoder.so proprietary/libOMX.TI.Video.encoder.so
adb pull /system/lib/libOMX.TI.WBAMR.encode.so proprietary/libOMX.TI.WBAMR.encode.so
adb pull /system/lib/libOMX_Core.so proprietary/libOMX_Core.so
adb pull /system/lib/libPERF.so proprietary/libPERF.so
adb pull /system/lib/libVendor_ti_omx.so proprietary/libVendor_ti_omx.so
adb pull /system/lib/libVendor_ti_omx_config_parser.so proprietary/libVendor_ti_omx_config_parser.so
adb pull /system/lib/libbattd.so proprietary/libbattd.so
adb pull /system/lib/libglslcompiler.so proprietary/libglslcompiler.so
adb pull /system/lib/libgtalk_jni.so proprietary/libgtalk_jni.so
adb pull /system/lib/libmoto_ril.so proprietary/libmoto_ril.so
adb pull /system/lib/liboemcamera.so proprietary/liboemcamera.so
adb pull /system/lib/libomx_wmadec_sharedlibrary.so proprietary/libomx_wmadec_sharedlibrary.so
adb pull /system/lib/libomx_wmvdec_sharedlibrary.so proprietary/libomx_wmvdec_sharedlibrary.so
adb pull /system/lib/libpppd_plugin-ril.so proprietary/libpppd_plugin-ril.so
adb pull /system/lib/libpvasfcommon.so proprietary/libpvasfcommon.so
adb pull /system/lib/libpvasflocalpb.so proprietary/libpvasflocalpb.so
adb pull /system/lib/libpvasflocalpbreg.so proprietary/libpvasflocalpbreg.so
adb pull /system/lib/libpvr2d.so proprietary/libpvr2d.so
adb pull /system/lib/libpvrANDROID_WSEGL.so proprietary/libpvrANDROID_WSEGL.so
adb pull /system/lib/libspeech.so proprietary/libspeech.so
adb pull /system/lib/libsrv_um.so proprietary/libsrv_um.so
adb pull /system/lib/modules/tiwlan_drv.ko proprietary/tiwlan_drv.ko
adb pull /system/lib/modules/wl127x_test.ko proprietary/wl127x_test.ko
adb pull /system/tts/lang_pico/de-DE_gl0_sg.bin proprietary/de-DE_gl0_sg.bin
adb pull /system/tts/lang_pico/de-DE_ta.bin proprietary/de-DE_ta.bin
adb pull /system/tts/lang_pico/en-GB_kh0_sg.bin proprietary/en-GB_kh0_sg.bin
adb pull /system/tts/lang_pico/en-GB_ta.bin proprietary/en-GB_ta.bin
adb pull /system/tts/lang_pico/en-US_lh0_sg.bin proprietary/en-US_lh0_sg.bin
adb pull /system/tts/lang_pico/en-US_ta.bin proprietary/en-US_ta.bin
adb pull /system/tts/lang_pico/es-ES_ta.bin proprietary/es-ES_ta.bin
adb pull /system/tts/lang_pico/es-ES_zl0_sg.bin proprietary/es-ES_zl0_sg.bin
adb pull /system/tts/lang_pico/fr-FR_nk0_sg.bin proprietary/fr-FR_nk0_sg.bin
adb pull /system/tts/lang_pico/fr-FR_ta.bin proprietary/fr-FR_ta.bin
adb pull /system/tts/lang_pico/it-IT_cm0_sg.bin proprietary/it-IT_cm0_sg.bin
adb pull /system/tts/lang_pico/it-IT_ta.bin proprietary/it-IT_ta.bin
adb pull /system/usr/keychars/sholes-keypad.kcm.bin proprietary/sholes-keypad.kcm.bin
adb pull /system/usr/keylayout/cpcap-key.kl proprietary/cpcap-key.kl
adb pull /system/usr/keylayout/sholes-keypad.kl proprietary/sholes-keypad.kl
