#!/bin/sh

mkdir -p proprietary

adb pull /system/lib/libmoto_gps.so proprietary
adb pull /system/lib/libaudio.so proprietary
adb pull /system/lib/libaudiopolicy.so proprietary
adb pull /system/lib/libcamera.so proprietary
adb pull /system/lib/libril_rds.so proprietary
adb pull /system/lib/libnmea.so proprietary

adb pull /system/bin/SaveBPVer proprietary
adb pull /system/bin/akmd2 proprietary
adb pull /system/bin/ap_gain.bin proprietary
adb pull /system/bin/battd proprietary
adb pull /system/bin/bthelp proprietary
adb pull /system/bin/chat-ril proprietary
adb pull /system/bin/ftmipcd proprietary
adb pull /system/bin/mdm_panicd proprietary
adb pull /system/bin/picd proprietary
adb pull /system/bin/pppd-ril proprietary
adb pull /system/bin/pvrsrvinit proprietary
adb pull /system/bin/tcmd proprietary
adb pull /system/etc/cameraCalFileDef.bin proprietary
adb pull /system/etc/excluded-input-devices.xml proprietary
adb pull /system/etc/firmware/wl1271.bin proprietary
adb pull /system/etc/gps.conf proprietary
adb pull /system/etc/motorola/12m/key_code_map.txt proprietary
adb pull /system/etc/permissions/android.hardware.camera.flash-autofocus.xml proprietary
adb pull /system/etc/permissions/android.hardware.sensor.light.xml proprietary
adb pull /system/etc/permissions/android.hardware.sensor.proximity.xml proprietary
adb pull /system/etc/permissions/android.hardware.telephony.cdma.xml proprietary
adb pull /system/etc/permissions/android.hardware.touchscreen.multitouch.xml proprietary
adb pull /system/etc/ppp/peers/pppd-ril.options proprietary
adb pull /system/etc/pvasflocal.cfg proprietary
adb pull /system/etc/vendor/cpcap/macro_data proprietary
adb pull /system/etc/vendor/cpcap/vector_data proprietary
adb pull /system/etc/vold.conf proprietary
adb pull /system/etc/wifi/fw_wlan1271.bin proprietary
adb pull /system/lib/dsp/baseimage.dof proprietary
adb pull /system/lib/dsp/conversions.dll64P proprietary
adb pull /system/lib/dsp/h264vdec_sn.dll64P proprietary
adb pull /system/lib/dsp/h264venc_sn.dll64P proprietary
adb pull /system/lib/dsp/jpegenc_sn.dll64P proprietary
adb pull /system/lib/dsp/m4venc_sn.dll64P proprietary
adb pull /system/lib/dsp/mp4vdec_sn.dll64P proprietary
adb pull /system/lib/dsp/mpeg4aacenc_sn.dll64P proprietary
adb pull /system/lib/dsp/nbamrenc_sn.dll64P proprietary
adb pull /system/lib/dsp/postprocessor_dualout.dll64P proprietary
adb pull /system/lib/dsp/ringio.dll64P proprietary
adb pull /system/lib/dsp/usn.dll64P proprietary
adb pull /system/lib/dsp/wbamrenc_sn.dll64P proprietary
adb pull /system/lib/egl/libEGL_POWERVR_SGX530_121.so proprietary
adb pull /system/lib/egl/libGLESv1_CM_POWERVR_SGX530_121.so proprietary
adb pull /system/lib/egl/libGLESv2_POWERVR_SGX530_121.so proprietary
adb pull /system/lib/hw/gralloc.omap3.so proprietary
adb pull /system/lib/hw/lights.sholes.so proprietary
adb pull /system/lib/hw/sensors.sholes.so proprietary
adb pull /system/lib/libHPImgApi.so proprietary
adb pull /system/lib/libIMGegl.so proprietary
adb pull /system/lib/libbattd.so proprietary
adb pull /system/lib/libglslcompiler.so proprietary
adb pull /system/lib/libgtalk_jni.so proprietary
adb pull /system/lib/libmoto_ril.so proprietary
adb pull /system/lib/liboemcamera.so proprietary
adb pull /system/lib/libomx_wmadec_sharedlibrary.so proprietary
adb pull /system/lib/libomx_wmvdec_sharedlibrary.so proprietary
adb pull /system/lib/libpppd_plugin-ril.so proprietary
adb pull /system/lib/libpvasfcommon.so proprietary
adb pull /system/lib/libpvasflocalpb.so proprietary
adb pull /system/lib/libpvasflocalpbreg.so proprietary
adb pull /system/lib/libpvr2d.so proprietary
adb pull /system/lib/libpvrANDROID_WSEGL.so proprietary
adb pull /system/lib/libspeech.so proprietary
adb pull /system/lib/libsrv_um.so proprietary
adb pull /system/tts/lang_pico/de-DE_gl0_sg.bin proprietary
adb pull /system/tts/lang_pico/de-DE_ta.bin proprietary
adb pull /system/tts/lang_pico/en-GB_kh0_sg.bin proprietary
adb pull /system/tts/lang_pico/en-GB_ta.bin proprietary
adb pull /system/tts/lang_pico/en-US_lh0_sg.bin proprietary
adb pull /system/tts/lang_pico/en-US_ta.bin proprietary
adb pull /system/tts/lang_pico/es-ES_ta.bin proprietary
adb pull /system/tts/lang_pico/es-ES_zl0_sg.bin proprietary
adb pull /system/tts/lang_pico/fr-FR_nk0_sg.bin proprietary
adb pull /system/tts/lang_pico/fr-FR_ta.bin proprietary
adb pull /system/tts/lang_pico/it-IT_cm0_sg.bin proprietary
adb pull /system/tts/lang_pico/it-IT_ta.bin proprietary
adb pull /system/usr/keychars/sholes-keypad.kcm.bin proprietary
adb pull /system/usr/keylayout/cpcap-key.kl proprietary
adb pull /system/usr/keylayout/sholes-keypad.kl proprietary
adb pull /system/etc/01_Vendor_ti_omx.cfg proprietary
adb pull /system/etc/contributors.css proprietary
adb pull /system/etc/contributors.html proprietary
adb pull /system/etc/permissions/android.software.live_wallpaper.xml proprietary
adb pull /system/lib/libLCML.so proprietary
adb pull /system/lib/libOMX.TI.AAC.encode.so proprietary
adb pull /system/lib/libOMX.TI.AMR.encode.so proprietary
adb pull /system/lib/libOMX.TI.JPEG.Encoder.so proprietary
adb pull /system/lib/libOMX.TI.Video.Decoder.so proprietary
adb pull /system/lib/libOMX.TI.Video.encoder.so proprietary
adb pull /system/lib/libOMX.TI.WBAMR.encode.so proprietary
adb pull /system/lib/libOMX_Core.so proprietary
adb pull /system/lib/libPERF.so proprietary
adb pull /system/lib/libVendor_ti_omx.so proprietary
adb pull /system/lib/libVendor_ti_omx_config_parser.so proprietary
adb pull /system/lib/libopencore_author.so proprietary